# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Livibility' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
 
  pod 'FSCalendar', '~> 2.8'
end



  # Pods for Livibility

  target 'LivibilityTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LivibilityUITests' do
    # Pods for testing
  end
   workspace 'Livibility'

post_install do |installer|
    installer.pods_project.build_configurations.each do |config|
        config.build_settings.delete('CODE_SIGNING_ALLOWED')
        config.build_settings.delete('CODE_SIGNING_REQUIRED')
    end
end
